<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MateriaSeeder extends Seeder
{
    
    public function run()
    {
        DB::table('materia_curso')->insert([
            ['horas_semana' => '12','materia_id' => '1','curso_id' => '1'],
            ['horas_semana' => '12','materia_id' => '1','curso_id' => '2'],
            ['horas_semana' => '20','materia_id' => '1','curso_id' => '3'],
            ['horas_semana' => '20','materia_id' => '1','curso_id' => '4'],
            ['horas_semana' => '32','materia_id' => '1','curso_id' => '5'],
            ['horas_semana' => '32','materia_id' => '1','curso_id' => '6'],
            ['horas_semana' => '16','materia_id' => '2','curso_id' => '1'],
            ['horas_semana' => '16','materia_id' => '2','curso_id' => '2'],
            ['horas_semana' => '16','materia_id' => '2','curso_id' => '3'],
            ['horas_semana' => '16','materia_id' => '2','curso_id' => '4'],
            ['horas_semana' => '16','materia_id' => '2','curso_id' => '5'],
            ['horas_semana' => '16','materia_id' => '2','curso_id' => '6'],
            ['horas_semana' => '20','materia_id' => '3','curso_id' => '1'],
            ['horas_semana' => '20','materia_id' => '3','curso_id' => '2'],
            ['horas_semana' => '20','materia_id' => '3','curso_id' => '3'],
            ['horas_semana' => '20','materia_id' => '3','curso_id' => '4'],
            ['horas_semana' => '20','materia_id' => '3','curso_id' => '5'],
            ['horas_semana' => '20','materia_id' => '3','curso_id' => '6'],
            ['horas_semana' => '24','materia_id' => '4','curso_id' => '1'],
            ['horas_semana' => '24','materia_id' => '4','curso_id' => '2'],
            ['horas_semana' => '24','materia_id' => '4','curso_id' => '3'],
            ['horas_semana' => '16','materia_id' => '4','curso_id' => '4'],
            ['horas_semana' => '12','materia_id' => '4','curso_id' => '5'],
            ['horas_semana' => '12','materia_id' => '4','curso_id' => '6'],
            ['horas_semana' => '8','materia_id' => '5','curso_id' => '1'],
            ['horas_semana' => '8','materia_id' => '5','curso_id' => '2'],
            ['horas_semana' => '8','materia_id' => '5','curso_id' => '3'],
            ['horas_semana' => '8','materia_id' => '5','curso_id' => '4'],
            ['horas_semana' => '8','materia_id' => '5','curso_id' => '5'],
            ['horas_semana' => '8','materia_id' => '5','curso_id' => '6'],
            ['horas_semana' => '8','materia_id' => '6','curso_id' => '1'],
            ['horas_semana' => '8','materia_id' => '6','curso_id' => '2'],
            ['horas_semana' => '8','materia_id' => '6','curso_id' => '3'],
            ['horas_semana' => '8','materia_id' => '6','curso_id' => '4'],
            ['horas_semana' => '8','materia_id' => '6','curso_id' => '5'],
            ['horas_semana' => '8','materia_id' => '6','curso_id' => '6'],
            ['horas_semana' => '8','materia_id' => '7','curso_id' => '3'],
            ['horas_semana' => '8','materia_id' => '7','curso_id' => '4'],
            ['horas_semana' => '8','materia_id' => '7','curso_id' => '5'],
            ['horas_semana' => '8','materia_id' => '7','curso_id' => '6'],
            ['horas_semana' => '8','materia_id' => '8','curso_id' => '3'],
            ['horas_semana' => '8','materia_id' => '8','curso_id' => '4'],
            ['horas_semana' => '8','materia_id' => '8','curso_id' => '5'],
            ['horas_semana' => '8','materia_id' => '8','curso_id' => '6'],
            ['horas_semana' => '8','materia_id' => '9','curso_id' => '1'],
            ['horas_semana' => '8','materia_id' => '9','curso_id' => '2'],
            ['horas_semana' => '8','materia_id' => '9','curso_id' => '3'],
            ['horas_semana' => '8','materia_id' => '9','curso_id' => '4'],
            ['horas_semana' => '8','materia_id' => '9','curso_id' => '5'],
            ['horas_semana' => '8','materia_id' => '9','curso_id' => '6'],
            ['horas_semana' => '16','materia_id' => '10','curso_id' => '1'],
            ['horas_semana' => '16','materia_id' => '10','curso_id' => '2'],
            ['horas_semana' => '32','materia_id' => '10','curso_id' => '3'],
            ['horas_semana' => '32','materia_id' => '10','curso_id' => '4'],
            ['horas_semana' => '48','materia_id' => '11','curso_id' => '5'],
            ['horas_semana' => '48','materia_id' => '11','curso_id' => '6'],
            ['horas_semana' => '8','materia_id' => '12','curso_id' => '1'],
            ['horas_semana' => '8','materia_id' => '12','curso_id' => '2'],
            ['horas_semana' => '8','materia_id' => '12','curso_id' => '3'],
            ['horas_semana' => '8','materia_id' => '12','curso_id' => '4'],
            ['horas_semana' => '8','materia_id' => '12','curso_id' => '5'],
            ['horas_semana' => '8','materia_id' => '12','curso_id' => '6'],
            ['horas_semana' => '8','materia_id' => '13','curso_id' => '1'],
            ['horas_semana' => '8','materia_id' => '13','curso_id' => '2'],
            ['horas_semana' => '8','materia_id' => '13','curso_id' => '3'],
            ['horas_semana' => '8','materia_id' => '13','curso_id' => '4'],
            ['horas_semana' => '8','materia_id' => '13','curso_id' => '5'],
            ['horas_semana' => '8','materia_id' => '13','curso_id' => '6'],
            ['horas_semana' => '8','materia_id' => '14','curso_id' => '1'],
            ['horas_semana' => '8','materia_id' => '14','curso_id' => '2'],
            ['horas_semana' => '8','materia_id' => '14','curso_id' => '3'],
            ['horas_semana' => '8','materia_id' => '14','curso_id' => '4'],
            ['horas_semana' => '8','materia_id' => '14','curso_id' => '5'],
            ['horas_semana' => '8','materia_id' => '14','curso_id' => '6'],
        ]);
    }
}
